title: "CS-E4740 Federated Learning"
description: "A simple Jekyll site for GitHub Pages"
author: "Alexander Jung"
baseurl: "" # Leave blank for root
url: "https://FederatedLearningAalto.github.io" # Replace with your GitHub Pages URL
